future: true
permalink: /:title/
url: http://hustcat.github.io
name: YY哥
author: hustcat
qq: 
email: hustcat@gmail.com
duoshuo: hustcat
beian: 
cnzz: 
weibo: hustcat
github: hustcat
paginate: 20
truncate: true
about: "YY哥(hustcat)"
