future: true
permalink: /:title/
url: http://blog.ihaiu.com
name: 爱海游
author: ihaiu
qq: 593705098
email: ihaiu@qq.com
duoshuo: blogihaiu
beian: 
cnzz: 1260003113
weibo: zengfeng75
github: ihaiucom
paginate: 20
truncate: true
about: "爱海游"