future: true
permalink: /:title/
url: http://blog.ihaiu.com
name: 爱海游
author: ihaiu
qq: 
email: ihaiu@qq.com
duoshuo: 海游
beian: 
cnzz: 
weibo: zengfeng75
github: ihaiucom
paginate: 20
truncate: true
about: "爱海游"
