import {GamerLoginS2CHandler} from "./GamerLoginS2CHandler";
import {GamerLoginGetDataS2CHandler} from "./GamerLoginGetDataS2CHandler";
import {ServerTimeS2CHandler} from "./ServerTimeS2CHandler";
import {GamerNotifyLoginOtherS2CHandler} from "./GamerNotifyLoginOtherS2CHandler";
import {GamerSubChatChannelS2CHandler} from "./GamerSubChatChannelS2CHandler";
import {GamerChangeNameS2CHandler} from "./GamerChangeNameS2CHandler";
import {GamerChangeAvatarS2CHandler} from "./GamerChangeAvatarS2CHandler";
import {GamerNotifyExpLevelS2CHandler} from "./GamerNotifyExpLevelS2CHandler";
import {GamerGetBackpackS2CHandler} from "./GamerGetBackpackS2CHandler";
import {GamerNotifyItemChangeS2CHandler} from "./GamerNotifyItemChangeS2CHandler";
import {GamerSellItemS2CHandler} from "./GamerSellItemS2CHandler";
import {GamerUseItemS2CHandler} from "./GamerUseItemS2CHandler";
import {GamerFriendChatS2CHandler} from "./GamerFriendChatS2CHandler";
import {GamerWorldChatS2CHandler} from "./GamerWorldChatS2CHandler";
import {GamerTestChatS2CHandler} from "./GamerTestChatS2CHandler";
import {GamerClubRequestS2CHandler} from "./GamerClubRequestS2CHandler";
import {GamerNotifyNewChatS2CHandler} from "./GamerNotifyNewChatS2CHandler";
import {GamerNewFriendReqS2CHandler} from "./GamerNewFriendReqS2CHandler";
import {GamerDelFriendS2CHandler} from "./GamerDelFriendS2CHandler";
import {GamerNotifyNewFriendReqS2CHandler} from "./GamerNotifyNewFriendReqS2CHandler";
import {GamerProcessFriendReqS2CHandler} from "./GamerProcessFriendReqS2CHandler";
import {GamerNotifyNewFriendS2CHandler} from "./GamerNotifyNewFriendS2CHandler";
import {GamerNotifyDelFriendS2CHandler} from "./GamerNotifyDelFriendS2CHandler";
import {GamerNotifyNoticeS2CHandler} from "./GamerNotifyNoticeS2CHandler";
import {GamerNotifyMailS2CHandler} from "./GamerNotifyMailS2CHandler";
import {GamerNotifyNewMailS2CHandler} from "./GamerNotifyNewMailS2CHandler";
import {GamerGetMailS2CHandler} from "./GamerGetMailS2CHandler";
import {GamerDelMailS2CHandler} from "./GamerDelMailS2CHandler";
import {GamerDelHaveReadMailS2CHandler} from "./GamerDelHaveReadMailS2CHandler";
import {GamerOneKeyRcvMailRewardS2CHandler} from "./GamerOneKeyRcvMailRewardS2CHandler";
import {GamerChangeMailStateS2CHandler} from "./GamerChangeMailStateS2CHandler";
import {GamerNewHeroS2CHandler} from "./GamerNewHeroS2CHandler";
import {GamerUpgradeHeroS2CHandler} from "./GamerUpgradeHeroS2CHandler";
import {GamerUseHeroMedicineS2CHandler} from "./GamerUseHeroMedicineS2CHandler";
import {GamerUpStarHeroS2CHandler} from "./GamerUpStarHeroS2CHandler";
import {GamerUpHeroSkillS2CHandler} from "./GamerUpHeroSkillS2CHandler";
import {GamerGetHeroS2CHandler} from "./GamerGetHeroS2CHandler";
import {GamerNotifyHerosChangeS2CHandler} from "./GamerNotifyHerosChangeS2CHandler";
import {GamerNotifyHeroPropUpdateS2CHandler} from "./GamerNotifyHeroPropUpdateS2CHandler";
import {GamerPVPLoadingS2CHandler} from "./GamerPVPLoadingS2CHandler";
import {GamerNotifyPVPLoadingS2CHandler} from "./GamerNotifyPVPLoadingS2CHandler";
import {GamerPVPSyncS2CHandler} from "./GamerPVPSyncS2CHandler";
import {GamerNotifyGamerMiniS2CHandler} from "./GamerNotifyGamerMiniS2CHandler";
import {GamerNotifyPVPSyncS2CHandler} from "./GamerNotifyPVPSyncS2CHandler";
import {GamerNotifyNewPVPResultS2CHandler} from "./GamerNotifyNewPVPResultS2CHandler";
import {GamerReliveS2CHandler} from "./GamerReliveS2CHandler";
import {GamerNotifyIconChangeS2CHandler} from "./GamerNotifyIconChangeS2CHandler";
import {GamerNotifyDiamonChangeS2CHandler} from "./GamerNotifyDiamonChangeS2CHandler";
import {GamerNotifyEnergyChangeS2CHandler} from "./GamerNotifyEnergyChangeS2CHandler";
import {GamerNotifyExpChangeS2CHandler} from "./GamerNotifyExpChangeS2CHandler";
import {GamerGetRealTimeRankS2CHandler} from "./GamerGetRealTimeRankS2CHandler";
import {GamerCheckPVPBattleS2CHandler} from "./GamerCheckPVPBattleS2CHandler";
import {GamerUploadWXInfoS2CHandler} from "./GamerUploadWXInfoS2CHandler";
import {GamerGetNoviceGuideS2CHandler} from "./GamerGetNoviceGuideS2CHandler";
import {GamerNoviceGuideChangeS2CHandler} from "./GamerNoviceGuideChangeS2CHandler";
import {GamerMatchS2CHandler} from "./GamerMatchS2CHandler";
import {GamerCancelMatchS2CHandler} from "./GamerCancelMatchS2CHandler";
import {GamerNotifyMatchInfoS2CHandler} from "./GamerNotifyMatchInfoS2CHandler";
import {GamerGetRewardS2CHandler} from "./GamerGetRewardS2CHandler";
import {GamerUseIconS2CHandler} from "./GamerUseIconS2CHandler";
import {GamerNotifyGashaponInfoS2CHandler} from "./GamerNotifyGashaponInfoS2CHandler";
import {GamerExtractGashaponS2CHandler} from "./GamerExtractGashaponS2CHandler";
import {GamerGetGashaponPreviewS2CHandler} from "./GamerGetGashaponPreviewS2CHandler";
import {GamerNotifyActivitiesS2CHandler} from "./GamerNotifyActivitiesS2CHandler";
import {GetActivityRewardS2CHandler} from "./GetActivityRewardS2CHandler";
import {CreateGuildS2CHandler} from "./CreateGuildS2CHandler";
import {GuildGamerLoginS2CHandler} from "./GuildGamerLoginS2CHandler";
import {GuildGamerLoginoutS2CHandler} from "./GuildGamerLoginoutS2CHandler";
import {DissolutionGuildS2CHandler} from "./DissolutionGuildS2CHandler";
import {GetGuildS2CHandler} from "./GetGuildS2CHandler";
import {GetGuildListS2CHandler} from "./GetGuildListS2CHandler";
import {GamerNotifyApplyJoinGuildS2CHandler} from "./GamerNotifyApplyJoinGuildS2CHandler";
import {ApplyJoinGuildS2CHandler} from "./ApplyJoinGuildS2CHandler";
import {ApprovalJoinGuildS2CHandler} from "./ApprovalJoinGuildS2CHandler";
import {GamerNotifyInviteJoinGuildS2CHandler} from "./GamerNotifyInviteJoinGuildS2CHandler";
import {InviteJoinGuildS2CHandler} from "./InviteJoinGuildS2CHandler";
import {AgreeJoinGuildS2CHandler} from "./AgreeJoinGuildS2CHandler";
import {QuitGuildS2CHandler} from "./QuitGuildS2CHandler";
import {KickOutGuildS2CHandler} from "./KickOutGuildS2CHandler";
import {GamerNotifyGuildMemUpdateS2CHandler} from "./GamerNotifyGuildMemUpdateS2CHandler";
import {GuildChatS2CHandler} from "./GuildChatS2CHandler";
import {GamerNotifyGuildChatS2CHandler} from "./GamerNotifyGuildChatS2CHandler";
import {GMS2CHandler} from "./GMS2CHandler";
import {CheckPointListS2CHandler} from "./CheckPointListS2CHandler";
import {GamerNotifyCheckPointListS2CHandler} from "./GamerNotifyCheckPointListS2CHandler";
import {GamerNotifyNewCheckPointListS2CHandler} from "./GamerNotifyNewCheckPointListS2CHandler";
import {GamerNotifyRewardS2CHandler} from "./GamerNotifyRewardS2CHandler";
import {GetPlotStarRewardS2CHandler} from "./GetPlotStarRewardS2CHandler";
import {BuyTimesCheckPointS2CHandler} from "./BuyTimesCheckPointS2CHandler";
import {SweepCheckPointS2CHandler} from "./SweepCheckPointS2CHandler";
import {GamerSettlePVES2CHandler} from "./GamerSettlePVES2CHandler";
import {DraugListS2CHandler} from "./DraugListS2CHandler";
import {AwakenDraugS2CHandler} from "./AwakenDraugS2CHandler";
import {PutDraugIntoPackS2CHandler} from "./PutDraugIntoPackS2CHandler";
import {SwallowDraugS2CHandler} from "./SwallowDraugS2CHandler";
import {DecomposeDraugS2CHandler} from "./DecomposeDraugS2CHandler";
import {LockDraugS2CHandler} from "./LockDraugS2CHandler";
import {WearDraugS2CHandler} from "./WearDraugS2CHandler";
import {UnwearDraugS2CHandler} from "./UnwearDraugS2CHandler";
import {DraugSelectHeroS2CHandler} from "./DraugSelectHeroS2CHandler";
import {HeroGroupListS2CHandler} from "./HeroGroupListS2CHandler";
import {UnlockHeroGroupS2CHandler} from "./UnlockHeroGroupS2CHandler";
import {ChangeNameHeroGroupS2CHandler} from "./ChangeNameHeroGroupS2CHandler";
import {GamerNotifyUnlockPosHeroGroupS2CHandler} from "./GamerNotifyUnlockPosHeroGroupS2CHandler";
import {HeroGroupChangeHeroS2CHandler} from "./HeroGroupChangeHeroS2CHandler";
import {HeroGroupChangeSkillS2CHandler} from "./HeroGroupChangeSkillS2CHandler";
import {BuyFatigueS2CHandler} from "./BuyFatigueS2CHandler";
import {GetFatigueWelfareS2CHandler} from "./GetFatigueWelfareS2CHandler";
import {GamerNotifyFatigueS2CHandler} from "./GamerNotifyFatigueS2CHandler";
import {UpStarEquipS2CHandler} from "./UpStarEquipS2CHandler";
import {EatEquipsS2CHandler} from "./EatEquipsS2CHandler";
import {DesEquipS2CHandler} from "./DesEquipS2CHandler";
import {TakeOnEquipS2CHandler} from "./TakeOnEquipS2CHandler";
import {TakeOffEquipS2CHandler} from "./TakeOffEquipS2CHandler";
import {RedSpotS2CHandler} from "./RedSpotS2CHandler";
import {MakeTeamS2CHandler} from "./MakeTeamS2CHandler";
import {SetTeamAimS2CHandler} from "./SetTeamAimS2CHandler";
import {JoinTeamS2CHandler} from "./JoinTeamS2CHandler";
import {ExitTeamS2CHandler} from "./ExitTeamS2CHandler";
import {TurnOverTeamLeaderS2CHandler} from "./TurnOverTeamLeaderS2CHandler";
import {InviteTeamS2CHandler} from "./InviteTeamS2CHandler";
import {RejectTeamS2CHandler} from "./RejectTeamS2CHandler";
import {GamerNotifyTeamS2CHandler} from "./GamerNotifyTeamS2CHandler";
import {GamerNotifyTeamInfoS2CHandler} from "./GamerNotifyTeamInfoS2CHandler";
import {GamerNotifyTeamChangeS2CHandler} from "./GamerNotifyTeamChangeS2CHandler";
import {GamerNotifyTeamMemberChangeS2CHandler} from "./GamerNotifyTeamMemberChangeS2CHandler";
import {GamerNotifyLeaveTeamS2CHandler} from "./GamerNotifyLeaveTeamS2CHandler";
import {KickTeamS2CHandler} from "./KickTeamS2CHandler";
import {SetTeamHelpS2CHandler} from "./SetTeamHelpS2CHandler";
import {SetTeamHeroS2CHandler} from "./SetTeamHeroS2CHandler";
import {SwitchTeamReadyS2CHandler} from "./SwitchTeamReadyS2CHandler";
import {GamerNotifyTeamReadyS2CHandler} from "./GamerNotifyTeamReadyS2CHandler";
import {TeamBattleS2CHandler} from "./TeamBattleS2CHandler";
import {GetDanInfoS2CHandler} from "./GetDanInfoS2CHandler";
import {GamerNotifyDanInfoS2CHandler} from "./GamerNotifyDanInfoS2CHandler";
import {GamerNotifyNewSeasonS2CHandler} from "./GamerNotifyNewSeasonS2CHandler";
import {GetDuelRankS2CHandler} from "./GetDuelRankS2CHandler";
import {SysListS2CHandler} from "./SysListS2CHandler";
import {SysOpenShowS2CHandler} from "./SysOpenShowS2CHandler";
import {GetQuestsS2CHandler} from "./GetQuestsS2CHandler";
import {GamerNotifyQuestsS2CHandler} from "./GamerNotifyQuestsS2CHandler";
import {GetQuestRewardS2CHandler} from "./GetQuestRewardS2CHandler";
import {GetDailyQuestRewardS2CHandler} from "./GetDailyQuestRewardS2CHandler";
import {GamerHeroImageChooseS2CHandler} from "./GamerHeroImageChooseS2CHandler";
import {GamerHeroImageChangeS2CHandler} from "./GamerHeroImageChangeS2CHandler";
import {GamerBuyRollS2CHandler} from "./GamerBuyRollS2CHandler";
import {GetGamerSecretLandS2CHandler} from "./GetGamerSecretLandS2CHandler";
import {GamerNotifyGamerSecretLandInfoS2CHandler} from "./GamerNotifyGamerSecretLandInfoS2CHandler";
import {GamerNotifySecretLandInfoS2CHandler} from "./GamerNotifySecretLandInfoS2CHandler";
import {GamerSecretLandBattleRewardS2CHandler} from "./GamerSecretLandBattleRewardS2CHandler";
import {GamerSecretLandWeekRewardS2CHandler} from "./GamerSecretLandWeekRewardS2CHandler";
import {GamerSecretLandRankS2CHandler} from "./GamerSecretLandRankS2CHandler";
import {GetGamerSecretLandInfoS2CHandler} from "./GetGamerSecretLandInfoS2CHandler";
import {GamerNotifySLTreasureBoxS2CHandler} from "./GamerNotifySLTreasureBoxS2CHandler";
import {GamerNotifyNewSecretLandResultS2CHandler} from "./GamerNotifyNewSecretLandResultS2CHandler";
import {GamerChangeItemIsSawS2CHandler} from "./GamerChangeItemIsSawS2CHandler";

export default class ProtoHandlerList
{
	GamerLoginS2C = GamerLoginS2CHandler;
	GamerLoginGetDataS2C = GamerLoginGetDataS2CHandler;
	ServerTimeS2C = ServerTimeS2CHandler;
	GamerNotifyLoginOtherS2C = GamerNotifyLoginOtherS2CHandler;
	GamerSubChatChannelS2C = GamerSubChatChannelS2CHandler;
	GamerChangeNameS2C = GamerChangeNameS2CHandler;
	GamerChangeAvatarS2C = GamerChangeAvatarS2CHandler;
	GamerNotifyExpLevelS2C = GamerNotifyExpLevelS2CHandler;
	GamerGetBackpackS2C = GamerGetBackpackS2CHandler;
	GamerNotifyItemChangeS2C = GamerNotifyItemChangeS2CHandler;
	GamerSellItemS2C = GamerSellItemS2CHandler;
	GamerUseItemS2C = GamerUseItemS2CHandler;
	GamerFriendChatS2C = GamerFriendChatS2CHandler;
	GamerWorldChatS2C = GamerWorldChatS2CHandler;
	GamerTestChatS2C = GamerTestChatS2CHandler;
	GamerClubRequestS2C = GamerClubRequestS2CHandler;
	GamerNotifyNewChatS2C = GamerNotifyNewChatS2CHandler;
	GamerNewFriendReqS2C = GamerNewFriendReqS2CHandler;
	GamerDelFriendS2C = GamerDelFriendS2CHandler;
	GamerNotifyNewFriendReqS2C = GamerNotifyNewFriendReqS2CHandler;
	GamerProcessFriendReqS2C = GamerProcessFriendReqS2CHandler;
	GamerNotifyNewFriendS2C = GamerNotifyNewFriendS2CHandler;
	GamerNotifyDelFriendS2C = GamerNotifyDelFriendS2CHandler;
	GamerNotifyNoticeS2C = GamerNotifyNoticeS2CHandler;
	GamerNotifyMailS2C = GamerNotifyMailS2CHandler;
	GamerNotifyNewMailS2C = GamerNotifyNewMailS2CHandler;
	GamerGetMailS2C = GamerGetMailS2CHandler;
	GamerDelMailS2C = GamerDelMailS2CHandler;
	GamerDelHaveReadMailS2C = GamerDelHaveReadMailS2CHandler;
	GamerOneKeyRcvMailRewardS2C = GamerOneKeyRcvMailRewardS2CHandler;
	GamerChangeMailStateS2C = GamerChangeMailStateS2CHandler;
	GamerNewHeroS2C = GamerNewHeroS2CHandler;
	GamerUpgradeHeroS2C = GamerUpgradeHeroS2CHandler;
	GamerUseHeroMedicineS2C = GamerUseHeroMedicineS2CHandler;
	GamerUpStarHeroS2C = GamerUpStarHeroS2CHandler;
	GamerUpHeroSkillS2C = GamerUpHeroSkillS2CHandler;
	GamerGetHeroS2C = GamerGetHeroS2CHandler;
	GamerNotifyHerosChangeS2C = GamerNotifyHerosChangeS2CHandler;
	GamerNotifyHeroPropUpdateS2C = GamerNotifyHeroPropUpdateS2CHandler;
	GamerPVPLoadingS2C = GamerPVPLoadingS2CHandler;
	GamerNotifyPVPLoadingS2C = GamerNotifyPVPLoadingS2CHandler;
	GamerPVPSyncS2C = GamerPVPSyncS2CHandler;
	GamerNotifyGamerMiniS2C = GamerNotifyGamerMiniS2CHandler;
	GamerNotifyPVPSyncS2C = GamerNotifyPVPSyncS2CHandler;
	GamerNotifyNewPVPResultS2C = GamerNotifyNewPVPResultS2CHandler;
	GamerReliveS2C = GamerReliveS2CHandler;
	GamerNotifyIconChangeS2C = GamerNotifyIconChangeS2CHandler;
	GamerNotifyDiamonChangeS2C = GamerNotifyDiamonChangeS2CHandler;
	GamerNotifyEnergyChangeS2C = GamerNotifyEnergyChangeS2CHandler;
	GamerNotifyExpChangeS2C = GamerNotifyExpChangeS2CHandler;
	GamerGetRealTimeRankS2C = GamerGetRealTimeRankS2CHandler;
	GamerCheckPVPBattleS2C = GamerCheckPVPBattleS2CHandler;
	GamerUploadWXInfoS2C = GamerUploadWXInfoS2CHandler;
	GamerGetNoviceGuideS2C = GamerGetNoviceGuideS2CHandler;
	GamerNoviceGuideChangeS2C = GamerNoviceGuideChangeS2CHandler;
	GamerMatchS2C = GamerMatchS2CHandler;
	GamerCancelMatchS2C = GamerCancelMatchS2CHandler;
	GamerNotifyMatchInfoS2C = GamerNotifyMatchInfoS2CHandler;
	GamerGetRewardS2C = GamerGetRewardS2CHandler;
	GamerUseIconS2C = GamerUseIconS2CHandler;
	GamerNotifyGashaponInfoS2C = GamerNotifyGashaponInfoS2CHandler;
	GamerExtractGashaponS2C = GamerExtractGashaponS2CHandler;
	GamerGetGashaponPreviewS2C = GamerGetGashaponPreviewS2CHandler;
	GamerNotifyActivitiesS2C = GamerNotifyActivitiesS2CHandler;
	GetActivityRewardS2C = GetActivityRewardS2CHandler;
	CreateGuildS2C = CreateGuildS2CHandler;
	GuildGamerLoginS2C = GuildGamerLoginS2CHandler;
	GuildGamerLoginoutS2C = GuildGamerLoginoutS2CHandler;
	DissolutionGuildS2C = DissolutionGuildS2CHandler;
	GetGuildS2C = GetGuildS2CHandler;
	GetGuildListS2C = GetGuildListS2CHandler;
	GamerNotifyApplyJoinGuildS2C = GamerNotifyApplyJoinGuildS2CHandler;
	ApplyJoinGuildS2C = ApplyJoinGuildS2CHandler;
	ApprovalJoinGuildS2C = ApprovalJoinGuildS2CHandler;
	GamerNotifyInviteJoinGuildS2C = GamerNotifyInviteJoinGuildS2CHandler;
	InviteJoinGuildS2C = InviteJoinGuildS2CHandler;
	AgreeJoinGuildS2C = AgreeJoinGuildS2CHandler;
	QuitGuildS2C = QuitGuildS2CHandler;
	KickOutGuildS2C = KickOutGuildS2CHandler;
	GamerNotifyGuildMemUpdateS2C = GamerNotifyGuildMemUpdateS2CHandler;
	GuildChatS2C = GuildChatS2CHandler;
	GamerNotifyGuildChatS2C = GamerNotifyGuildChatS2CHandler;
	GMS2C = GMS2CHandler;
	CheckPointListS2C = CheckPointListS2CHandler;
	GamerNotifyCheckPointListS2C = GamerNotifyCheckPointListS2CHandler;
	GamerNotifyNewCheckPointListS2C = GamerNotifyNewCheckPointListS2CHandler;
	GamerNotifyRewardS2C = GamerNotifyRewardS2CHandler;
	GetPlotStarRewardS2C = GetPlotStarRewardS2CHandler;
	BuyTimesCheckPointS2C = BuyTimesCheckPointS2CHandler;
	SweepCheckPointS2C = SweepCheckPointS2CHandler;
	GamerSettlePVES2C = GamerSettlePVES2CHandler;
	DraugListS2C = DraugListS2CHandler;
	AwakenDraugS2C = AwakenDraugS2CHandler;
	PutDraugIntoPackS2C = PutDraugIntoPackS2CHandler;
	SwallowDraugS2C = SwallowDraugS2CHandler;
	DecomposeDraugS2C = DecomposeDraugS2CHandler;
	LockDraugS2C = LockDraugS2CHandler;
	WearDraugS2C = WearDraugS2CHandler;
	UnwearDraugS2C = UnwearDraugS2CHandler;
	DraugSelectHeroS2C = DraugSelectHeroS2CHandler;
	HeroGroupListS2C = HeroGroupListS2CHandler;
	UnlockHeroGroupS2C = UnlockHeroGroupS2CHandler;
	ChangeNameHeroGroupS2C = ChangeNameHeroGroupS2CHandler;
	GamerNotifyUnlockPosHeroGroupS2C = GamerNotifyUnlockPosHeroGroupS2CHandler;
	HeroGroupChangeHeroS2C = HeroGroupChangeHeroS2CHandler;
	HeroGroupChangeSkillS2C = HeroGroupChangeSkillS2CHandler;
	BuyFatigueS2C = BuyFatigueS2CHandler;
	GetFatigueWelfareS2C = GetFatigueWelfareS2CHandler;
	GamerNotifyFatigueS2C = GamerNotifyFatigueS2CHandler;
	UpStarEquipS2C = UpStarEquipS2CHandler;
	EatEquipsS2C = EatEquipsS2CHandler;
	DesEquipS2C = DesEquipS2CHandler;
	TakeOnEquipS2C = TakeOnEquipS2CHandler;
	TakeOffEquipS2C = TakeOffEquipS2CHandler;
	RedSpotS2C = RedSpotS2CHandler;
	MakeTeamS2C = MakeTeamS2CHandler;
	SetTeamAimS2C = SetTeamAimS2CHandler;
	JoinTeamS2C = JoinTeamS2CHandler;
	ExitTeamS2C = ExitTeamS2CHandler;
	TurnOverTeamLeaderS2C = TurnOverTeamLeaderS2CHandler;
	InviteTeamS2C = InviteTeamS2CHandler;
	RejectTeamS2C = RejectTeamS2CHandler;
	GamerNotifyTeamS2C = GamerNotifyTeamS2CHandler;
	GamerNotifyTeamInfoS2C = GamerNotifyTeamInfoS2CHandler;
	GamerNotifyTeamChangeS2C = GamerNotifyTeamChangeS2CHandler;
	GamerNotifyTeamMemberChangeS2C = GamerNotifyTeamMemberChangeS2CHandler;
	GamerNotifyLeaveTeamS2C = GamerNotifyLeaveTeamS2CHandler;
	KickTeamS2C = KickTeamS2CHandler;
	SetTeamHelpS2C = SetTeamHelpS2CHandler;
	SetTeamHeroS2C = SetTeamHeroS2CHandler;
	SwitchTeamReadyS2C = SwitchTeamReadyS2CHandler;
	GamerNotifyTeamReadyS2C = GamerNotifyTeamReadyS2CHandler;
	TeamBattleS2C = TeamBattleS2CHandler;
	GetDanInfoS2C = GetDanInfoS2CHandler;
	GamerNotifyDanInfoS2C = GamerNotifyDanInfoS2CHandler;
	GamerNotifyNewSeasonS2C = GamerNotifyNewSeasonS2CHandler;
	GetDuelRankS2C = GetDuelRankS2CHandler;
	SysListS2C = SysListS2CHandler;
	SysOpenShowS2C = SysOpenShowS2CHandler;
	GetQuestsS2C = GetQuestsS2CHandler;
	GamerNotifyQuestsS2C = GamerNotifyQuestsS2CHandler;
	GetQuestRewardS2C = GetQuestRewardS2CHandler;
	GetDailyQuestRewardS2C = GetDailyQuestRewardS2CHandler;
	GamerHeroImageChooseS2C = GamerHeroImageChooseS2CHandler;
	GamerHeroImageChangeS2C = GamerHeroImageChangeS2CHandler;
	GamerBuyRollS2C = GamerBuyRollS2CHandler;
	GetGamerSecretLandS2C = GetGamerSecretLandS2CHandler;
	GamerNotifyGamerSecretLandInfoS2C = GamerNotifyGamerSecretLandInfoS2CHandler;
	GamerNotifySecretLandInfoS2C = GamerNotifySecretLandInfoS2CHandler;
	GamerSecretLandBattleRewardS2C = GamerSecretLandBattleRewardS2CHandler;
	GamerSecretLandWeekRewardS2C = GamerSecretLandWeekRewardS2CHandler;
	GamerSecretLandRankS2C = GamerSecretLandRankS2CHandler;
	GetGamerSecretLandInfoS2C = GetGamerSecretLandInfoS2CHandler;
	GamerNotifySLTreasureBoxS2C = GamerNotifySLTreasureBoxS2CHandler;
	GamerNotifyNewSecretLandResultS2C = GamerNotifyNewSecretLandResultS2CHandler;
	GamerChangeItemIsSawS2C = GamerChangeItemIsSawS2CHandler;

	init()
	{
		this.GamerLoginS2C.bind(this);
		this.GamerLoginGetDataS2C.bind(this);
		this.ServerTimeS2C.bind(this);
		this.GamerNotifyLoginOtherS2C.bind(this);
		this.GamerSubChatChannelS2C.bind(this);
		this.GamerChangeNameS2C.bind(this);
		this.GamerChangeAvatarS2C.bind(this);
		this.GamerNotifyExpLevelS2C.bind(this);
		this.GamerGetBackpackS2C.bind(this);
		this.GamerNotifyItemChangeS2C.bind(this);
		this.GamerSellItemS2C.bind(this);
		this.GamerUseItemS2C.bind(this);
		this.GamerFriendChatS2C.bind(this);
		this.GamerWorldChatS2C.bind(this);
		this.GamerTestChatS2C.bind(this);
		this.GamerClubRequestS2C.bind(this);
		this.GamerNotifyNewChatS2C.bind(this);
		this.GamerNewFriendReqS2C.bind(this);
		this.GamerDelFriendS2C.bind(this);
		this.GamerNotifyNewFriendReqS2C.bind(this);
		this.GamerProcessFriendReqS2C.bind(this);
		this.GamerNotifyNewFriendS2C.bind(this);
		this.GamerNotifyDelFriendS2C.bind(this);
		this.GamerNotifyNoticeS2C.bind(this);
		this.GamerNotifyMailS2C.bind(this);
		this.GamerNotifyNewMailS2C.bind(this);
		this.GamerGetMailS2C.bind(this);
		this.GamerDelMailS2C.bind(this);
		this.GamerDelHaveReadMailS2C.bind(this);
		this.GamerOneKeyRcvMailRewardS2C.bind(this);
		this.GamerChangeMailStateS2C.bind(this);
		this.GamerNewHeroS2C.bind(this);
		this.GamerUpgradeHeroS2C.bind(this);
		this.GamerUseHeroMedicineS2C.bind(this);
		this.GamerUpStarHeroS2C.bind(this);
		this.GamerUpHeroSkillS2C.bind(this);
		this.GamerGetHeroS2C.bind(this);
		this.GamerNotifyHerosChangeS2C.bind(this);
		this.GamerNotifyHeroPropUpdateS2C.bind(this);
		this.GamerPVPLoadingS2C.bind(this);
		this.GamerNotifyPVPLoadingS2C.bind(this);
		this.GamerPVPSyncS2C.bind(this);
		this.GamerNotifyGamerMiniS2C.bind(this);
		this.GamerNotifyPVPSyncS2C.bind(this);
		this.GamerNotifyNewPVPResultS2C.bind(this);
		this.GamerReliveS2C.bind(this);
		this.GamerNotifyIconChangeS2C.bind(this);
		this.GamerNotifyDiamonChangeS2C.bind(this);
		this.GamerNotifyEnergyChangeS2C.bind(this);
		this.GamerNotifyExpChangeS2C.bind(this);
		this.GamerGetRealTimeRankS2C.bind(this);
		this.GamerCheckPVPBattleS2C.bind(this);
		this.GamerUploadWXInfoS2C.bind(this);
		this.GamerGetNoviceGuideS2C.bind(this);
		this.GamerNoviceGuideChangeS2C.bind(this);
		this.GamerMatchS2C.bind(this);
		this.GamerCancelMatchS2C.bind(this);
		this.GamerNotifyMatchInfoS2C.bind(this);
		this.GamerGetRewardS2C.bind(this);
		this.GamerUseIconS2C.bind(this);
		this.GamerNotifyGashaponInfoS2C.bind(this);
		this.GamerExtractGashaponS2C.bind(this);
		this.GamerGetGashaponPreviewS2C.bind(this);
		this.GamerNotifyActivitiesS2C.bind(this);
		this.GetActivityRewardS2C.bind(this);
		this.CreateGuildS2C.bind(this);
		this.GuildGamerLoginS2C.bind(this);
		this.GuildGamerLoginoutS2C.bind(this);
		this.DissolutionGuildS2C.bind(this);
		this.GetGuildS2C.bind(this);
		this.GetGuildListS2C.bind(this);
		this.GamerNotifyApplyJoinGuildS2C.bind(this);
		this.ApplyJoinGuildS2C.bind(this);
		this.ApprovalJoinGuildS2C.bind(this);
		this.GamerNotifyInviteJoinGuildS2C.bind(this);
		this.InviteJoinGuildS2C.bind(this);
		this.AgreeJoinGuildS2C.bind(this);
		this.QuitGuildS2C.bind(this);
		this.KickOutGuildS2C.bind(this);
		this.GamerNotifyGuildMemUpdateS2C.bind(this);
		this.GuildChatS2C.bind(this);
		this.GamerNotifyGuildChatS2C.bind(this);
		this.GMS2C.bind(this);
		this.CheckPointListS2C.bind(this);
		this.GamerNotifyCheckPointListS2C.bind(this);
		this.GamerNotifyNewCheckPointListS2C.bind(this);
		this.GamerNotifyRewardS2C.bind(this);
		this.GetPlotStarRewardS2C.bind(this);
		this.BuyTimesCheckPointS2C.bind(this);
		this.SweepCheckPointS2C.bind(this);
		this.GamerSettlePVES2C.bind(this);
		this.DraugListS2C.bind(this);
		this.AwakenDraugS2C.bind(this);
		this.PutDraugIntoPackS2C.bind(this);
		this.SwallowDraugS2C.bind(this);
		this.DecomposeDraugS2C.bind(this);
		this.LockDraugS2C.bind(this);
		this.WearDraugS2C.bind(this);
		this.UnwearDraugS2C.bind(this);
		this.DraugSelectHeroS2C.bind(this);
		this.HeroGroupListS2C.bind(this);
		this.UnlockHeroGroupS2C.bind(this);
		this.ChangeNameHeroGroupS2C.bind(this);
		this.GamerNotifyUnlockPosHeroGroupS2C.bind(this);
		this.HeroGroupChangeHeroS2C.bind(this);
		this.HeroGroupChangeSkillS2C.bind(this);
		this.BuyFatigueS2C.bind(this);
		this.GetFatigueWelfareS2C.bind(this);
		this.GamerNotifyFatigueS2C.bind(this);
		this.UpStarEquipS2C.bind(this);
		this.EatEquipsS2C.bind(this);
		this.DesEquipS2C.bind(this);
		this.TakeOnEquipS2C.bind(this);
		this.TakeOffEquipS2C.bind(this);
		this.RedSpotS2C.bind(this);
		this.MakeTeamS2C.bind(this);
		this.SetTeamAimS2C.bind(this);
		this.JoinTeamS2C.bind(this);
		this.ExitTeamS2C.bind(this);
		this.TurnOverTeamLeaderS2C.bind(this);
		this.InviteTeamS2C.bind(this);
		this.RejectTeamS2C.bind(this);
		this.GamerNotifyTeamS2C.bind(this);
		this.GamerNotifyTeamInfoS2C.bind(this);
		this.GamerNotifyTeamChangeS2C.bind(this);
		this.GamerNotifyTeamMemberChangeS2C.bind(this);
		this.GamerNotifyLeaveTeamS2C.bind(this);
		this.KickTeamS2C.bind(this);
		this.SetTeamHelpS2C.bind(this);
		this.SetTeamHeroS2C.bind(this);
		this.SwitchTeamReadyS2C.bind(this);
		this.GamerNotifyTeamReadyS2C.bind(this);
		this.TeamBattleS2C.bind(this);
		this.GetDanInfoS2C.bind(this);
		this.GamerNotifyDanInfoS2C.bind(this);
		this.GamerNotifyNewSeasonS2C.bind(this);
		this.GetDuelRankS2C.bind(this);
		this.SysListS2C.bind(this);
		this.SysOpenShowS2C.bind(this);
		this.GetQuestsS2C.bind(this);
		this.GamerNotifyQuestsS2C.bind(this);
		this.GetQuestRewardS2C.bind(this);
		this.GetDailyQuestRewardS2C.bind(this);
		this.GamerHeroImageChooseS2C.bind(this);
		this.GamerHeroImageChangeS2C.bind(this);
		this.GamerBuyRollS2C.bind(this);
		this.GetGamerSecretLandS2C.bind(this);
		this.GamerNotifyGamerSecretLandInfoS2C.bind(this);
		this.GamerNotifySecretLandInfoS2C.bind(this);
		this.GamerSecretLandBattleRewardS2C.bind(this);
		this.GamerSecretLandWeekRewardS2C.bind(this);
		this.GamerSecretLandRankS2C.bind(this);
		this.GetGamerSecretLandInfoS2C.bind(this);
		this.GamerNotifySLTreasureBoxS2C.bind(this);
		this.GamerNotifyNewSecretLandResultS2C.bind(this);
		this.GamerChangeItemIsSawS2C.bind(this);

	}
}