/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class BigUI extends Laya.Scene {
		public _list:Laya.List;
        public static  uiView:any ={"type":"Scene","props":{"width":610,"height":757},"compId":2,"child":[{"type":"Sprite","props":{"y":0,"x":0,"texture":"test/2.png"},"compId":4},{"type":"List","props":{"y":104,"x":13,"width":585,"var":"_list","vScrollBarSkin":" ","spaceY":20,"repeatX":1,"height":629,"elasticEnabled":true},"compId":3,"child":[{"type":"bigItem","props":{"runtime":"view/bigItem.ts","renderType":"render"},"compId":5}]}],"loadList":["test/2.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(BigUI.uiView);
        }
    }
    REG("ui.test.BigUI",BigUI);
    export class BigItemUI extends Laya.View {
		public img_head:Laya.Image;
		public text_name:Laya.Label;
		public text_score:Laya.Label;
        public static  uiView:any ={"type":"View","props":{"width":580,"height":100},"compId":2,"child":[{"type":"Sprite","props":{"y":0,"x":0,"width":575,"texture":"test/3.png","height":99},"compId":7},{"type":"Image","props":{"y":6,"x":22,"width":80,"var":"img_head","skin":"test/4.png","height":80},"compId":3,"child":[{"type":"Sprite","props":{"y":-1,"x":-1,"width":82,"texture":"test/c1.png","renderType":"mask","height":82},"compId":10}]},{"type":"Label","props":{"y":38.5,"x":136,"width":259,"var":"text_name","text":"名字","overflow":"scroll","height":24,"fontSize":20,"font":"Microsoft YaHei","color":"#ffffff","align":"center"},"compId":4},{"type":"Label","props":{"y":42.5,"x":496,"var":"text_score","text":"分数","fontSize":20,"color":"#ffffff","align":"center"},"compId":5}],"loadList":["test/3.png","test/4.png","test/c1.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(BigItemUI.uiView);
        }
    }
    REG("ui.test.BigItemUI",BigItemUI);
}